version: "3.8"

services:
  app:
    container_name: wa_multi_session
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "1234:1234"
    restart: always
    networks:
      - checkervisor_network

networks:
  checkervisor_network:
    driver: bridge